[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "z"
strip = true

[workspace]
members = []
resolver = "2"

[workspace.dependencies]

[workspace.lints.clippy]
all = "warn"

[workspace.package]
edition = "2021"
version = "0.0.0"
