name: anti virus
on:
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-anti-virus
  cancel-in-progress: true
jobs:
  clamav:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: djdefi/gitavscan@main
        with:
          full: '--full'
